package migrations

import (
	"time"

	"github.com/amartin3659/HttpServerPractice/internal/models"
	"github.com/google/uuid"
)

func (m *Seed) seedPosts() {
	posts := []models.Post{
		// Posts for Emily Johnson (ID: 550e8400-e29b-41d4-a716-446655440000)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440000",
			Title:     "Exploring the Art of Photography",
			Body:      "In today's post, I want to share my passion for photography. Capturing moments in time allows us to relive memories and emotions. Whether it's a breathtaking landscape or a candid shot of a loved one, photography has the power to freeze time. I'll be sharing some of my favorite photography tips and tricks, hoping to inspire others to embark on their photographic journey.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440000",
			Title:     "Book Review: 'The Silent Symphony'",
			Body:      "Recently, I finished reading 'The Silent Symphony' by renowned author A. R. Thompson. This captivating novel takes readers on a journey through the intricate melodies of life, love, and loss. In my review, I'll delve into the author's masterful storytelling, exploring the characters, plot twists, and the profound themes that left a lasting impression on me.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440000",
			Title:     "Healthy Living: My Fitness Routine",
			Body:      "Maintaining a healthy lifestyle is crucial, and one aspect I prioritize is regular exercise. In this post, I'll share my fitness routine, including favorite workouts, tips for staying motivated, and the positive impact it has had on my overall well-being. Let's embark on this journey towards a healthier and happier life together!",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440000",
			Title:     "Reflections on Nature: A Hike in the Mountains",
			Body:      "Nature has a profound way of soothing the soul. Join me in reflecting on a recent hike in the mountains. The crisp air, towering trees, and panoramic views served as a reminder of the beauty that surrounds us. I'll share the awe-inspiring moments and the sense of tranquility that nature provides.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440000",
			Title:     "Diving into DIY Crafts: Creating Personalized Home Decor",
			Body:      "Expressing creativity through DIY crafts is both fun and rewarding. In this post, I'll take you through a recent project of creating personalized home decor items. From handmade wall art to customized furniture pieces, let's explore the joy of crafting and adding a personal touch to our living spaces.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440000",
			Title:     "Musical Moments: Discovering New Melodies",
			Body:      "Music has the power to evoke emotions and create unforgettable moments. Join me on a journey of discovering new melodies. I'll share recent music finds, from indie artists to classic compositions, and explore the stories behind the songs that have become the soundtrack of my life.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},

		// Posts for Alex Rodriguez (ID: 550e8400-e29b-41d4-a716-446655440001)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440001",
			Title:     "Tech Trends: Embracing the Future",
			Body:      "As a tech enthusiast, I'm always eager to explore the latest trends shaping our digital landscape. In this post, I'll discuss emerging technologies, from artificial intelligence to augmented reality, and their potential impact on our daily lives. Join me in navigating the exciting and ever-evolving world of technology!",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440001",
			Title:     "Culinary Adventures: A Foodie's Journey",
			Body:      "Embarking on culinary adventures is one of my favorite pastimes. From trying exotic dishes to mastering new recipes, I'll be sharing my foodie journey in this post. Join me as I explore the diverse world of flavors and share delightful experiences from my kitchen and beyond.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440001",
			Title:     "Travel Diaries: Discovering Hidden Gems",
			Body:      "Traveling opens our eyes to new cultures and experiences. In this post, I'll take you on a virtual journey to some of the hidden gems I've discovered during my recent travels. From charming local markets to breathtaking landscapes, let's explore the beauty of the world together.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440001",
			Title:     "Gaming Wonders: Exploring Virtual Realms",
			Body:      "Dive into the world of gaming with me as we explore virtual realms and captivating narratives. From epic adventures to strategic battles, I'll share my gaming experiences and recommendations for must-play titles. Join the discussion and let's celebrate the wonders of gaming!",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440001",
			Title:     "Entrepreneurial Insights: Navigating the Startup Journey",
			Body:      "Embarking on an entrepreneurial journey is both challenging and rewarding. In this post, I'll share insights and lessons learned from navigating the startup landscape. From ideation to execution, let's delve into the world of entrepreneurship and discuss the strategies for building a successful venture.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440001",
			Title:     "Fitness Fusion: A Holistic Approach to Well-being",
			Body:      "Discover a holistic approach to well-being with my fitness fusion journey. In this post, I'll explore the integration of physical exercise, mindfulness, and nutrition for overall health. Join me in embracing a balanced lifestyle that nurtures the body, mind, and spirit.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},

		// Posts for Sarah Patel (ID: 550e8400-e29b-41d4-a716-446655440002)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440002",
			Title:     "Mindfulness Meditation: Finding Inner Peace",
			Body:      "In today's fast-paced world, finding moments of calm is essential. Join me on a journey into mindfulness meditation, where I'll share techniques for cultivating inner peace and reducing stress. Discover the transformative power of mindfulness in improving overall well-being.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440002",
			Title:     "Artistic Expressions: Unleashing Creativity",
			Body:      "Expressing creativity is a fulfilling and enriching experience. In this post, I'll explore various artistic mediums, from painting to poetry, and how they serve as powerful tools for self-expression. Join me in the journey of unleashing creativity and embracing the beauty of artistic pursuits.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440002",
			Title:     "Tech Innovations: Shaping the Future",
			Body:      "As a tech enthusiast, I'm excited to delve into the latest innovations shaping the future. From breakthroughs in artificial intelligence to advancements in renewable energy, join me in exploring the transformative impact of technology on our lives and the world.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440002",
			Title:     "Culinary Delights: A Culinary World Tour",
			Body:      "Embark on a culinary world tour with me as we explore diverse cuisines and delightful flavors. From street food adventures to fine dining experiences, I'll share culinary delights that have left a lasting impression. Join me in savoring the richness of global gastronomy!",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440002",
			Title:     "Mindful Parenting: Nurturing Young Minds",
			Body:      "Parenting is a profound journey filled with joy and challenges. In this post, I'll share insights and practices of mindful parenting, focusing on creating a nurturing environment for young minds to flourish. Let's explore the transformative power of mindfulness in fostering a strong parent-child connection.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440002",
			Title:     "The Beauty of Nature: Capturing Serenity",
			Body:      "Immerse yourself in the beauty of nature through my lens as I capture serene landscapes and breathtaking scenes. In this post, I'll share my recent nature photography adventures, celebrating the wonders of the natural world. Join me in appreciating the tranquility and majesty of our surroundings.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},

		// Posts for Kevin Chen (ID: 550e8400-e29b-41d4-a716-446655440003)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440003",
			Title:     "Navigating the Financial Landscape: Smart Investing Tips",
			Body:      "Financial literacy is crucial for long-term success. Join me in navigating the financial landscape with smart investing tips. From understanding investment options to building a diversified portfolio, I'll share insights to help you make informed financial decisions and secure your financial future.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440003",
			Title:     "Fitness Motivation: Finding the Power Within",
			Body:      "Embark on a journey of fitness motivation as we explore the power within ourselves to achieve health and wellness goals. In this post, I'll share personal anecdotes, workout routines, and mindset strategies that have kept me motivated on the path to a healthier and more active lifestyle.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440003",
			Title:     "Exploring Cultural Heritage: A Journey Through History",
			Body:      "Delve into the rich tapestry of cultural heritage with me as we embark on a journey through history. In this post, I'll share experiences of exploring historical sites, traditions, and the vibrant stories that connect us to our cultural roots. Join me in celebrating the diversity and beauty of our global heritage.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440003",
			Title:     "Tech Enthusiast's Corner: Unboxing the Latest Gadgets",
			Body:      "Join me in the tech enthusiast's corner as we unbox and explore the latest gadgets hitting the market. From cutting-edge smartphones to innovative smart home devices, I'll share my thoughts on the features, functionalities, and the overall tech experience. Stay tuned for exciting tech discoveries!",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440003",
			Title:     "Mindful Eating: A Journey to Healthier Habits",
			Body:      "Mindful eating is a transformative practice that fosters a healthier relationship with food. In this post, I'll share insights into the mindful eating journey, exploring techniques to savor each bite, make conscious food choices, and cultivate a positive approach to nourishing our bodies.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440003",
			Title:     "Adventures in Literature: Must-Read Books of the Year",
			Body:      "Embark on literary adventures with me as we explore the must-read books of the year. From captivating novels to thought-provoking non-fiction, I'll share recommendations that have left a lasting impact. Join the reading journey and discover",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		// Posts for Jasmine Carter (ID: 550e8400-e29b-41d4-a716-446655440004)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440004",
			Title:     "Embracing Change: A Journey of Self-Discovery",
			Body:      "Change is the only constant in life, and in this post, I'll share my personal journey of embracing change as a catalyst for self-discovery. From navigating career shifts to exploring new hobbies, join me in finding the beauty and growth that come with embracing the inevitable twists and turns of life.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440004",
			Title:     "Navigating Parenthood: Lessons and Joys",
			Body:      "Parenthood is a remarkable journey filled with lessons and joys. In this post, I'll reflect on my experiences as a parent, sharing insights into the challenges, precious moments, and the profound impact that raising a child has had on my life. Join me in celebrating the beautiful journey of parenthood.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440004",
			Title:     "Empowering Women: Breaking Barriers",
			Body:      "Empowering women is a cause close to my heart. In this post, I'll discuss the importance of breaking barriers, challenging stereotypes, and fostering an environment where women can thrive. Join me in advocating for equality and empowerment in every aspect of life.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440004",
			Title:     "The Art of Networking: Building Meaningful Connections",
			Body:      "Networking goes beyond professional circles; it's about building meaningful connections that enrich our lives. In this post, I'll share tips on effective networking, whether in the professional world or personal endeavors. Join me in cultivating a network that adds value and support to our journey.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440004",
			Title:     "Mindful Living: Finding Balance in a Busy World",
			Body:      "Living mindfully is a conscious choice that leads to a more fulfilling life. In this post, I'll explore the practice of mindful living, sharing tips on finding balance amidst the hustle and bustle of daily life. Join me in the journey of cultivating presence and savoring each moment.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		// Posts for Ryan Thompson (ID: 550e8400-e29b-41d4-a716-446655440005)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440005",
			Title:     "Adventures in the Great Outdoors",
			Body:      "Nature is a playground for exploration, and in this post, I'll take you on some of my recent adventures in the great outdoors. From hiking scenic trails to camping under starlit skies, join me in embracing the beauty of nature and discovering the serenity it brings to our lives.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440005",
			Title:     "The Power of Music: A Personal Playlist",
			Body:      "Music has the incredible ability to evoke emotions and create lasting memories. In this post, I'll share my personal playlist, exploring the songs that hold special significance in my life. Join me in celebrating the diverse genres and melodies that shape our experiences and connect us with others.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440005",
			Title:     "Tech Talk: Navigating the Digital Landscape",
			Body:      "In the rapidly evolving world of technology, staying informed is key. Join me in this tech talk as we navigate the digital landscape, discussing the latest innovations, trends, and their impact on our daily lives. From gadgets to software, let's explore the exciting realm of technology together.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		// Posts for Olivia Davis (ID: 550e8400-e29b-41d4-a716-446655440006)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440006",
			Title:     "The Joy of Gardening: Cultivating Green Spaces",
			Body:      "Gardening is not just a hobby; it's a therapeutic journey that nurtures both plants and the soul. Join me in this post as I delve into the joy of gardening, sharing tips on creating green spaces, cultivating a variety of plants, and finding tranquility in the midst of nature's beauty.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440006",
			Title:     "Creative Cooking: Fusion Flavors in the Kitchen",
			Body:      "Cooking is an art, and in this post, I'll explore the world of creative cooking with a focus on fusion flavors. Join me in experimenting with diverse culinary influences, combining ingredients from different cuisines to create unique and delicious dishes that tantalize the taste buds.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440006",
			Title:     "The Art of Mindful Living: A Daily Practice",
			Body:      "Mindful living is a transformative practice that brings awareness to the present moment. In this post, I'll share insights into incorporating mindfulness into daily life, from mindful breathing exercises to cultivating gratitude. Join me in the journey of finding peace and fulfillment through mindful living.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440006",
			Title:     "Exploring Art Galleries: A Visual Feast",
			Body:      "Art has the power to inspire and evoke emotions, and in this post, I'll take you on a virtual tour of some captivating art galleries. From contemporary pieces to timeless classics, join me in exploring the visual feast that art offers and the stories it tells through different mediums.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440006",
			Title:     "Fitness Fusion: Mixing Up Workouts for Fun",
			Body:      "Keeping fitness enjoyable is essential for staying motivated. Join me in this post as I explore the concept of fitness fusion, combining various workouts for a fun and effective exercise routine. From dance-inspired workouts to outdoor activities, let's discover creative ways to stay active and healthy.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440006",
			Title:     "Literary Escapes: Book Recommendations for Every Mood",
			Body:      "Books have the magical ability to transport us to different worlds and emotions. In this post, I'll share a curated list of book recommendations for every mood – from uplifting novels to thought-provoking literature. Join me in exploring literary escapes that cater to a variety of reading preferences.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		// Posts for Marcus White (ID: 550e8400-e29b-41d4-a716-446655440007)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440007",
			Title:     "Entrepreneurial Insights: Navigating the Business Landscape",
			Body:      "Being an entrepreneur comes with its unique set of challenges and triumphs. In this post, I'll share insights gained from navigating the dynamic business landscape. From strategic decision-making to fostering innovation, join me in the journey of entrepreneurship and the lessons learned along the way.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440007",
			Title:     "Fitness Beyond the Gym: Outdoor Adventures",
			Body:      "Fitness is not confined to the walls of a gym. Join me in this post as we explore the exhilarating world of outdoor adventures for staying fit. From hiking scenic trails to embracing adrenaline-pumping activities, let's discover the joy of staying active while immersing ourselves in the beauty of nature.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		// Posts for Lauren Miller (ID: 550e8400-e29b-41d4-a716-446655440008)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440008",
			Title:     "Capturing Moments: The Art of Photography",
			Body:      "Photography allows us to freeze moments in time and create lasting memories. Join me in this post as I explore the art of photography, sharing tips on composition, storytelling, and capturing the essence of a moment. Let's embark on a visual journey together!",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440008",
			Title:     "Bookworm Chronicles: Recent Reads and Recommendations",
			Body:      "Diving into the world of books is a constant adventure. In this post, I'll share my recent literary explorations, providing insights into the captivating stories and thought-provoking narratives. Join me in the Bookworm Chronicles for book recommendations and discussions on the magic of reading.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440008",
			Title:     "Creative Cuisine: Culinary Experiments in the Kitchen",
			Body:      "Cooking is an art form that allows for endless creativity. Join me in this post as we delve into the realm of creative cuisine, experimenting with flavors, techniques, and unique recipes. From culinary adventures to delightful discoveries, let's explore the world of food together!",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440008",
			Title:     "Wanderlust Diaries: Travel Tales and Hidden Gems",
			Body:      "Traveling is a passion that opens doors to new experiences and cultures. In this post, I'll share travel tales, from exploring hidden gems to immersing in local traditions. Join me in the Wanderlust Diaries as we embark on virtual journeys around the world.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440008",
			Title:     "Mindful Living: Finding Balance in a Hectic World",
			Body:      "Amidst the hustle and bustle of daily life, finding balance is essential. Join me in this post as we explore the principles of mindful living, incorporating practices that promote well-being, self-awareness, and a sense of calm in the midst of a hectic world.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		// Posts for Brandon Lee (ID: 550e8400-e29b-41d4-a716-446655440009)
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440009",
			Title:     "Tech Trends Unveiled: Exploring the Future of Innovation",
			Body:      "In the ever-evolving world of technology, staying ahead is key. Join me in this post as we unveil the latest tech trends, from artificial intelligence to futuristic gadgets. Let's explore how these innovations are shaping the future and revolutionizing our daily lives.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440009",
			Title:     "Fitness Fusion: Blending Workouts for Optimal Health",
			Body:      "Fitness is a journey, and variety is the spice of a healthy lifestyle. Join me in this post as we explore the concept of fitness fusion, blending different workouts for a holistic approach to health. From strength training to mindfulness exercises, let's find a balanced and enjoyable fitness routine.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440009",
			Title:     "Entrepreneurial Insights: Lessons from the Business Trenches",
			Body:      "Being an entrepreneur is an exhilarating journey with its share of challenges and victories. In this post, I'll share entrepreneurial insights gleaned from the business trenches. From strategic decision-making to fostering innovation, let's navigate the dynamic world of entrepreneurship together.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440009",
			Title:     "Cinematic Explorations: Movie Magic and Beyond",
			Body:      "Movies are more than just entertainment; they are a form of art that captivates and inspires. Join me in this post as we embark on cinematic explorations, discussing movie magic, film reviews, and the impact of storytelling through the lens of the silver screen.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440009",
			Title:     "Beyond Borders: Cultural Immersions and Global Adventures",
			Body:      "Exploring different cultures is a journey of enrichment and understanding. In this post, I'll share tales of cultural immersions and global adventures. From tasting exotic cuisines to embracing local traditions, let's go beyond borders and celebrate the diversity that enriches our world.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		{
			ID:        uuid.New(),
			UserID:    "550e8400-e29b-41d4-a716-446655440009",
			Title:     "The Art of Coffee: A Brewtiful Exploration",
			Body:      "Coffee is more than just a beverage; it's a ritual, an art form. Join me in this post as we embark on a brewtiful exploration of the world of coffee. From specialty blends to brewing techniques, let's savor the nuances and aromas that make coffee a delightful part of our daily lives.",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
	}

	m.DB.Posts = append(m.DB.Posts, posts...)
}
